export const COUNTRY_CODES = [
  { code: '+91', flag: '🇮🇳', name: 'India', min: 10, max: 10 },
  { code: '+1', flag: '🇺🇸', name: 'United States', min: 10, max: 10 },
  { code: '+44', flag: '🇬🇧', name: 'United Kingdom', min: 10, max: 11 },
  { code: '+971', flag: '🇦🇪', name: 'UAE', min: 9, max: 9 },
  { code: '+65', flag: '🇸🇬', name: 'Singapore', min: 8, max: 8 },
  { code: '+61', flag: '🇦🇺', name: 'Australia', min: 9, max: 9 },
  { code: '+49', flag: '🇩🇪', name: 'Germany', min: 10, max: 11 },
  { code: '+81', flag: '🇯🇵', name: 'Japan', min: 10, max: 10 },
  { code: '+82', flag: '🇰🇷', name: 'South Korea', min: 9, max: 10 },
  { code: '+86', flag: '🇨🇳', name: 'China', min: 11, max: 11 },
  { code: '+33', flag: '🇫🇷', name: 'France', min: 9, max: 9 },
  { code: '+39', flag: '🇮🇹', name: 'Italy', min: 9, max: 10 },
  { code: '+55', flag: '🇧🇷', name: 'Brazil', min: 10, max: 11 },
  { code: '+7', flag: '🇷🇺', name: 'Russia', min: 10, max: 10 },
  { code: '+62', flag: '🇮🇩', name: 'Indonesia', min: 9, max: 13 },
  { code: '+63', flag: '🇵🇭', name: 'Philippines', min: 10, max: 10 },
  { code: '+66', flag: '🇹🇭', name: 'Thailand', min: 9, max: 9 },
  { code: '+84', flag: '🇻🇳', name: 'Vietnam', min: 9, max: 10 },
  { code: '+90', flag: '🇹🇷', name: 'Turkey', min: 10, max: 10 },
  { code: '+234', flag: '🇳🇬', name: 'Nigeria', min: 10, max: 11 },
  { code: '+27', flag: '🇿🇦', name: 'South Africa', min: 9, max: 9 },
  { code: '+52', flag: '🇲🇽', name: 'Mexico', min: 10, max: 10 },
  { code: '+60', flag: '🇲🇾', name: 'Malaysia', min: 9, max: 10 },
  { code: '+64', flag: '🇳🇿', name: 'New Zealand', min: 8, max: 10 },
  { code: '+48', flag: '🇵🇱', name: 'Poland', min: 9, max: 9 },
  { code: '+31', flag: '🇳🇱', name: 'Netherlands', min: 9, max: 9 },
  { code: '+46', flag: '🇸🇪', name: 'Sweden', min: 7, max: 13 },
  { code: '+41', flag: '🇨🇭', name: 'Switzerland', min: 9, max: 9 },
  { code: '+34', flag: '🇪🇸', name: 'Spain', min: 9, max: 9 },
  { code: '+351', flag: '🇵🇹', name: 'Portugal', min: 9, max: 9 },
  { code: '+92', flag: '🇵🇰', name: 'Pakistan', min: 10, max: 10 },
  { code: '+880', flag: '🇧🇩', name: 'Bangladesh', min: 10, max: 10 },
  { code: '+94', flag: '🇱🇰', name: 'Sri Lanka', min: 9, max: 9 },
  { code: '+977', flag: '🇳🇵', name: 'Nepal', min: 10, max: 10 },
  { code: '+20', flag: '🇪🇬', name: 'Egypt', min: 10, max: 10 },
  { code: '+966', flag: '🇸🇦', name: 'Saudi Arabia', min: 9, max: 9 },
  { code: '+974', flag: '🇶🇦', name: 'Qatar', min: 8, max: 8 },
  { code: '+968', flag: '🇴🇲', name: 'Oman', min: 8, max: 8 },
  { code: '+973', flag: '🇧🇭', name: 'Bahrain', min: 8, max: 8 },
  { code: '+965', flag: '🇰🇼', name: 'Kuwait', min: 8, max: 8 },
] as const;

export type Country = (typeof COUNTRY_CODES)[number];
