import {
  Activity,
  Bell,
  BookOpen,
  Database,
  ExternalLink,
  FileText,
  Image as ImageIcon,
  LifeBuoy,
  Lock,
  MessageCircle,
  MessageSquare,
  Monitor,
  Plus,
  ShieldCheck,
  Smartphone,
  Trash2,
  UserCheck,
  UserCircle,
  UserMinus,
} from 'lucide-react-native';
import { SettingsDirectoryEntry } from './types';

const G = {
  security: { groupLabel: 'Security & Privacy', groupOrder: 0 },
  app: { groupLabel: 'App Settings', groupOrder: 1 },
  help: { groupLabel: 'Help & Management', groupOrder: 2 },
} as const;

export const SETTINGS_DIRECTORY = [
  {
    id: 'privacy',
    stackScreenKey: 'privacy-security/privacy',
    href: '/privacy-security/privacy',
    title: 'Privacy',
    subtitle: 'Last seen, status, visibility',
    icon: ShieldCheck,
    keywords: ['last seen', 'status', 'visibility'],
    menu: { ...G.security, itemOrder: 0 },
  },
  {
    id: 'security',
    stackScreenKey: 'privacy-security/security',
    href: '/privacy-security/security',
    title: 'Security',
    subtitle: 'Biometric lock, device sessions',
    icon: Lock,
    keywords: ['biometric', 'lock', 'sessions', 'device'],
    menu: { ...G.security, itemOrder: 1 },
  },
  {
    id: 'notif',
    stackScreenKey: 'notifications/index',
    href: '/notifications',
    title: 'Notifications',
    subtitle: 'Message alerts, quiet hours',
    icon: Bell,
    keywords: ['alerts', 'quiet hours', 'push', 'sounds'],
    menu: { ...G.app, itemOrder: 0 },
  },
  {
    id: 'chat',
    stackScreenKey: 'chats/index',
    href: '/chats',
    title: 'Chats & Media',
    subtitle: 'Auto-download, wallpaper',
    icon: MessageSquare,
    keywords: ['chat', 'media', 'download', 'storage', 'wallpaper'],
    menu: { ...G.app, itemOrder: 1 },
  },
  {
    id: 'appearance',
    stackScreenKey: 'appearance/index',
    href: '/appearance',
    title: 'Appearance',
    subtitle: 'Theme & Personalization',
    icon: Monitor,
    keywords: ['theme', 'dark mode', 'light', 'personalization'],
    menu: { ...G.app, itemOrder: 2 },
  },
  {
    id: 'help',
    stackScreenKey: 'help-support/index',
    href: '/help-support',
    title: 'Help & Support',
    subtitle: 'Report a bug, terms of service',
    icon: LifeBuoy,
    keywords: ['bug', 'support', 'help', 'terms'],
    menu: { ...G.help, itemOrder: 0 },
  },
  {
    id: 'account-center',
    stackScreenKey: 'account-center/index',
    href: '/account-center',
    title: 'Account Center',
    subtitle: 'Delete account, personal data',
    icon: UserCircle,
    keywords: ['delete', 'data', 'deactivate', 'gdpr'],
    menu: { ...G.help, itemOrder: 1 },
  },
  {
    id: 'chat-wallpaper',
    stackScreenKey: 'chats/wallpaper',
    href: '/chats/wallpaper',
    title: 'Chat Wallpaper',
    subtitle: 'Background for your conversations',
    icon: ImageIcon,
    keywords: ['background', 'theme image', 'custom wallpaper'],
    searchContext: 'Chats & Media',
  },
  {
    id: 'network-usage',
    stackScreenKey: 'storage-data/network-usage',
    href: '/storage-data/network-usage',
    title: 'Network Usage',
    subtitle: 'Data sent and received in the app',
    icon: Database,
    keywords: ['data', 'bandwidth', 'wifi', 'cellular'],
    searchContext: 'Chats & Media',
  },
  {
    id: 'manage-storage',
    stackScreenKey: 'storage-data/storage',
    href: '/storage-data/storage',
    title: 'Manage Storage',
    subtitle: 'Clear caches and free space',
    icon: Trash2,
    keywords: ['cache', 'clear', 'space', 'storage'],
    searchContext: 'Chats & Media',
  },
  {
    id: 'support-chat',
    stackScreenKey: 'help-support/chat',
    href: '/help-support/chat',
    title: 'Direct Support',
    subtitle: 'Talk to our team',
    icon: MessageCircle,
    keywords: ['agent', 'human', 'ticket'],
    searchContext: 'Help & Support',
  },
  {
    id: 'knowledge-base',
    stackScreenKey: '(knowledge)/base',
    href: '/base',
    title: 'Knowledge Base',
    subtitle: 'Guides and tutorials',
    icon: BookOpen,
    keywords: ['faq', 'docs', 'how to', 'learn'],
    searchContext: 'Help & Support',
  },
  {
    id: 'feature-request',
    stackScreenKey: 'help-support/feature-request',
    href: '/help-support/feature-request',
    title: 'Feature Request',
    subtitle: 'Vote and suggest improvements',
    icon: ExternalLink,
    keywords: ['roadmap', 'vote', 'feedback', 'suggest'],
    searchContext: 'Help & Support',
  },
  {
    id: 'propose-feature',
    stackScreenKey: 'help-support/propose-feature',
    href: '/help-support/propose-feature',
    title: 'Propose Feature',
    subtitle: 'Submit a new idea',
    icon: Plus,
    keywords: ['new idea', 'suggestion', 'submit'],
    searchContext: 'Feature Request',
  },
  {
    id: 'terms-privacy',
    stackScreenKey: 'help-support/terms-privacy',
    href: '/help-support/terms-privacy',
    title: 'Terms & Privacy',
    subtitle: 'Legal and data policies',
    icon: FileText,
    keywords: ['legal', 'policy', 'tos', 'privacy policy'],
    searchContext: 'Help & Support',
  },
  {
    id: 'network-diagnostic',
    stackScreenKey: 'storage-data/network-diagnostic',
    href: '/storage-data/network-diagnostic',
    title: 'Network Diagnostic',
    subtitle: 'Connection health checks',
    icon: Activity,
    keywords: ['connection', 'ping', 'debug', 'internet'],
    searchContext: 'Help & Support',
  },
  {
    id: 'change-number',
    stackScreenKey: 'account-center/change-number',
    href: '/account-center/change-number',
    title: 'Change Phone Number',
    subtitle: 'Migrate account to a new number',
    icon: Smartphone,
    keywords: ['phone', 'migrate', 'sim', 'number'],
    searchContext: 'Account Center',
  },
  {
    id: 'request-info',
    stackScreenKey: 'account-center/request-info',
    href: '/account-center/request-info',
    title: 'Request Account Info',
    subtitle: 'Export your personal data report',
    icon: FileText,
    keywords: ['export', 'gdpr', 'download data', 'report'],
    searchContext: 'Account Center',
  },
  {
    id: 'deactivate',
    stackScreenKey: 'account-center/deactivate',
    href: '/account-center/deactivate',
    title: 'Deactivate Account',
    subtitle: 'Temporarily hide your profile',
    icon: UserMinus,
    keywords: ['pause', 'hide', 'temporary'],
    searchContext: 'Account Center',
  },
  {
    id: 'reactivate',
    stackScreenKey: 'account-center/reactivate',
    href: '/account-center/reactivate',
    title: 'Reactivate Account',
    subtitle: 'Make your profile visible again',
    icon: UserCheck,
    keywords: ['restore', 'undo deactivate'],
    searchContext: 'Account Center',
  },
  {
    id: 'delete-account',
    stackScreenKey: 'account-center/delete',
    href: '/account-center/delete',
    title: 'Delete My Account',
    subtitle: 'Permanently remove all data',
    icon: Trash2,
    keywords: ['erase', 'remove', 'forever'],
    searchContext: 'Account Center',
    destructive: true,
  },
] satisfies SettingsDirectoryEntry[];
